version: 1
update_configs:
  - package_manager: rust:cargo
    directory: /
    update_schedule: live
    automerged_updates:
      - match:
          dependency_type: all
          update_type: in_range
  - package_manager: javascript
    directory: /client
    update_schedule: live
    automerged_updates:
      - match:
          dependency_type: all
          update_type: in_range
